spring:
  config:
    import: file:.env[.properties]

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  structured:
    format:
      console: ""
  level:
    org.flywaydb: debug
