CREATE TABLE STORAGE_PROFILE (
    ID                                RAW(16)                        NOT NULL,
    ORGANIZATION_ID                   RAW(16)                        NOT NULL,
    CODE                              VARCHAR2(40 CHAR)              NOT NULL,
    NAME                              VARCHAR2(160 CHAR)             NOT NULL,
    PROFILE_VERSION                   NUMBER(6)                      NOT NULL,
    STATUS                            VARCHAR2(20 CHAR)              NOT NULL,
    MIN_CELSIUS                       NUMBER(5,2)                    NOT NULL,
    MAX_CELSIUS                       NUMBER(5,2)                    NOT NULL,
    MAX_SINGLE_EXCURSION_MINUTES      NUMBER(6)                      NOT NULL,
    MAX_CUMULATIVE_EXCURSION_MINUTES  NUMBER(6)                      NOT NULL,
    MIN_COVERAGE_PERCENT              NUMBER(5,2)                    NOT NULL,
    DELETED_AT                        TIMESTAMP(6) WITH TIME ZONE,
    LOCK_VERSION                      NUMBER(10)                     DEFAULT 0 NOT NULL,
    CREATED_AT                        TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_BY                        RAW(16)                        NOT NULL,
    UPDATED_AT                        TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY                        RAW(16),
    CONSTRAINT PK_STORAGE_PROFILE PRIMARY KEY (ID),
    CONSTRAINT FK_STORAGE_PROFILE_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID),
    CONSTRAINT CK_STORAGE_PROFILE_STATUS CHECK (STATUS IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    CONSTRAINT CK_STORAGE_PROFILE_CODE_BLANK CHECK (TRIM(CODE) IS NOT NULL),
    CONSTRAINT CK_STORAGE_PROFILE_NAME_BLANK CHECK (TRIM(NAME) IS NOT NULL),
    CONSTRAINT CK_STORAGE_PROFILE_RANGE CHECK (MIN_CELSIUS < MAX_CELSIUS),
    CONSTRAINT CK_STORAGE_PROFILE_EXCURSION CHECK (MAX_SINGLE_EXCURSION_MINUTES <= MAX_CUMULATIVE_EXCURSION_MINUTES),
    CONSTRAINT CK_STORAGE_PROFILE_COVERAGE CHECK (MIN_COVERAGE_PERCENT BETWEEN 0 AND 100),
    CONSTRAINT CK_STORAGE_PROFILE_VERSION CHECK (PROFILE_VERSION > 0)
);

CREATE INDEX IX_STORAGE_PROFILE_ORGANIZATION_ID ON STORAGE_PROFILE (ORGANIZATION_ID);

CREATE UNIQUE INDEX UX_STORAGE_PROFILE_CODE_LIVE ON STORAGE_PROFILE (
    CASE WHEN DELETED_AT IS NULL THEN ORGANIZATION_ID END,
    CASE WHEN DELETED_AT IS NULL THEN UPPER(CODE) END,
    CASE WHEN DELETED_AT IS NULL THEN PROFILE_VERSION END);

CREATE TABLE PRODUCT (
    ID                  RAW(16)                        NOT NULL,
    ORGANIZATION_ID     RAW(16)                        NOT NULL,
    STORAGE_PROFILE_ID  RAW(16)                        NOT NULL,
    SKU                 VARCHAR2(60 CHAR)              NOT NULL,
    NAME                VARCHAR2(160 CHAR)             NOT NULL,
    DELETED_AT          TIMESTAMP(6) WITH TIME ZONE,
    LOCK_VERSION        NUMBER(10)                     DEFAULT 0 NOT NULL,
    CREATED_AT          TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_BY          RAW(16)                        NOT NULL,
    UPDATED_AT          TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY          RAW(16),
    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUCT_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID),
    CONSTRAINT FK_PRODUCT_STORAGE_PROFILE FOREIGN KEY (STORAGE_PROFILE_ID) REFERENCES STORAGE_PROFILE (ID),
    CONSTRAINT CK_PRODUCT_SKU_BLANK CHECK (TRIM(SKU) IS NOT NULL),
    CONSTRAINT CK_PRODUCT_NAME_BLANK CHECK (TRIM(NAME) IS NOT NULL)
);

CREATE INDEX IX_PRODUCT_ORGANIZATION_ID ON PRODUCT (ORGANIZATION_ID);

CREATE INDEX IX_PRODUCT_STORAGE_PROFILE_ID ON PRODUCT (STORAGE_PROFILE_ID);

CREATE UNIQUE INDEX UX_PRODUCT_SKU_LIVE ON PRODUCT (
    CASE WHEN DELETED_AT IS NULL THEN ORGANIZATION_ID END,
    CASE WHEN DELETED_AT IS NULL THEN UPPER(SKU) END);

CREATE TABLE SITE (
    ID               RAW(16)                        NOT NULL,
    ORGANIZATION_ID  RAW(16)                        NOT NULL,
    CODE             VARCHAR2(40 CHAR)              NOT NULL,
    NAME             VARCHAR2(160 CHAR)             NOT NULL,
    KIND             VARCHAR2(20 CHAR)              NOT NULL,
    LATITUDE         NUMBER(9,6)                    NOT NULL,
    LONGITUDE        NUMBER(9,6)                    NOT NULL,
    TIME_ZONE        VARCHAR2(64 CHAR)              NOT NULL,
    DELETED_AT       TIMESTAMP(6) WITH TIME ZONE,
    LOCK_VERSION     NUMBER(10)                     DEFAULT 0 NOT NULL,
    CREATED_AT       TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_BY       RAW(16)                        NOT NULL,
    UPDATED_AT       TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY       RAW(16),
    CONSTRAINT PK_SITE PRIMARY KEY (ID),
    CONSTRAINT FK_SITE_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID),
    CONSTRAINT CK_SITE_KIND CHECK (KIND IN ('ORIGIN', 'DESTINATION', 'CROSS_DOCK')),
    CONSTRAINT CK_SITE_CODE_BLANK CHECK (TRIM(CODE) IS NOT NULL),
    CONSTRAINT CK_SITE_NAME_BLANK CHECK (TRIM(NAME) IS NOT NULL),
    CONSTRAINT CK_SITE_TIME_ZONE_BLANK CHECK (TRIM(TIME_ZONE) IS NOT NULL),
    CONSTRAINT CK_SITE_LATITUDE CHECK (LATITUDE BETWEEN -90 AND 90),
    CONSTRAINT CK_SITE_LONGITUDE CHECK (LONGITUDE BETWEEN -180 AND 180)
);

CREATE INDEX IX_SITE_ORGANIZATION_ID ON SITE (ORGANIZATION_ID);

CREATE UNIQUE INDEX UX_SITE_CODE_LIVE ON SITE (
    CASE WHEN DELETED_AT IS NULL THEN ORGANIZATION_ID END,
    CASE WHEN DELETED_AT IS NULL THEN UPPER(CODE) END);
