CREATE TABLE SHIPMENT (
    ID                                 RAW(16)                        NOT NULL,
    ORGANIZATION_ID                    RAW(16)                        NOT NULL,
    REFERENCE                          VARCHAR2(40 CHAR)              NOT NULL,
    STATUS                             VARCHAR2(20 CHAR)              NOT NULL,
    ORIGIN_SITE_ID                     RAW(16)                        NOT NULL,
    DESTINATION_SITE_ID                RAW(16)                        NOT NULL,
    CONSIGNEE_ORGANIZATION_ID          RAW(16)                        NOT NULL,
    CURRENT_CUSTODIAN_ORGANIZATION_ID  RAW(16)                        NOT NULL,
    DEVICE_ID                          RAW(16),
    MIN_CELSIUS                        NUMBER(5,2),
    MAX_CELSIUS                        NUMBER(5,2),
    MAX_SINGLE_EXCURSION_MINUTES       NUMBER(6),
    MAX_CUMULATIVE_EXCURSION_MINUTES   NUMBER(6),
    MIN_COVERAGE_PERCENT               NUMBER(5,2),
    OPEN_EXCURSION            NUMBER(1)     DEFAULT 0        NOT NULL,
    DISPATCHED_AT                      TIMESTAMP(6) WITH TIME ZONE,
    CLOSED_AT                          TIMESTAMP(6) WITH TIME ZONE,
    LOCK_VERSION                       NUMBER(10)                     DEFAULT 0 NOT NULL,
    CREATED_AT                         TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_BY                         RAW(16)                        NOT NULL,
    UPDATED_AT                         TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY                         RAW(16),
    CONSTRAINT PK_SHIPMENT PRIMARY KEY (ID),
    CONSTRAINT FK_SHIPMENT_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID),
    CONSTRAINT CK_SHIPMENT_STATUS CHECK (STATUS IN
        ('DRAFT', 'IN_TRANSIT', 'AT_DESTINATION', 'DELIVERED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT CK_SHIPMENT_REFERENCE_BLANK CHECK (TRIM(REFERENCE) IS NOT NULL),
    CONSTRAINT CK_SHIPMENT_OPEN_EXCURSION CHECK (OPEN_EXCURSION IN (0,1)),
    CONSTRAINT CK_SHIPMENT_THRESHOLDS CHECK (
        (MIN_CELSIUS IS NULL AND MAX_CELSIUS IS NULL AND MAX_SINGLE_EXCURSION_MINUTES IS NULL
            AND MAX_CUMULATIVE_EXCURSION_MINUTES IS NULL AND MIN_COVERAGE_PERCENT IS NULL)
        OR (MIN_CELSIUS IS NOT NULL AND MAX_CELSIUS IS NOT NULL AND MAX_SINGLE_EXCURSION_MINUTES IS NOT NULL
            AND MAX_CUMULATIVE_EXCURSION_MINUTES IS NOT NULL AND MIN_COVERAGE_PERCENT IS NOT NULL)),
    CONSTRAINT CK_SHIPMENT_RANGE CHECK (MIN_CELSIUS IS NULL OR MIN_CELSIUS < MAX_CELSIUS)
);

CREATE INDEX IX_SHIPMENT_ORGANIZATION_ID ON SHIPMENT (ORGANIZATION_ID);

CREATE UNIQUE INDEX UX_SHIPMENT_REFERENCE ON SHIPMENT (ORGANIZATION_ID, UPPER(REFERENCE));

CREATE TABLE SHIPMENT_LINE (
    ID               RAW(16)                        NOT NULL,
    SHIPMENT_ID      RAW(16)                        NOT NULL,
    PRODUCT_ID       RAW(16)                        NOT NULL,
    PRODUCT_NAME     VARCHAR2(160 CHAR)             NOT NULL,
    PROFILE_VERSION  NUMBER(6)                      NOT NULL,
    QUANTITY         NUMBER(12,3)                   NOT NULL,
    UNIT             VARCHAR2(16 CHAR)              NOT NULL,
    CREATED_AT       TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_BY       RAW(16)                        NOT NULL,
    UPDATED_AT       TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY       RAW(16),
    CONSTRAINT PK_SHIPMENT_LINE PRIMARY KEY (ID),
    CONSTRAINT FK_SHIPMENT_LINE_SHIPMENT FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENT (ID) ON DELETE CASCADE,
    CONSTRAINT CK_SHIPMENT_LINE_QUANTITY CHECK (QUANTITY > 0),
    CONSTRAINT CK_SHIPMENT_LINE_NAME_BLANK CHECK (TRIM(PRODUCT_NAME) IS NOT NULL),
    CONSTRAINT CK_SHIPMENT_LINE_UNIT_BLANK CHECK (TRIM(UNIT) IS NOT NULL)
);

CREATE INDEX IX_SHIPMENT_LINE_SHIPMENT_ID ON SHIPMENT_LINE (SHIPMENT_ID);

CREATE TABLE SHIPMENT_PARTICIPANT (
    ID               RAW(16)                        NOT NULL,
    SHIPMENT_ID      RAW(16)                        NOT NULL,
    ORGANIZATION_ID  RAW(16)                        NOT NULL,
    PARTICIPATION    VARCHAR2(20 CHAR)              NOT NULL,
    REVOKED_AT       TIMESTAMP(6) WITH TIME ZONE,
    LOCK_VERSION     NUMBER(10)                     DEFAULT 0 NOT NULL,
    CREATED_AT       TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_BY       RAW(16)                        NOT NULL,
    UPDATED_AT       TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY       RAW(16),
    CONSTRAINT PK_SHIPMENT_PARTICIPANT PRIMARY KEY (ID),
    CONSTRAINT FK_SHIPMENT_PARTICIPANT_SHIPMENT FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENT (ID) ON DELETE CASCADE,
    CONSTRAINT FK_SHIPMENT_PARTICIPANT_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID),
    CONSTRAINT CK_SHIPMENT_PARTICIPANT_PARTICIPATION CHECK (PARTICIPATION IN
        ('SHIPPER', 'CARRIER', 'CONSIGNEE', 'OBSERVER'))
);

CREATE INDEX IX_SHIPMENT_PARTICIPANT_SHIPMENT_ID ON SHIPMENT_PARTICIPANT (SHIPMENT_ID);

CREATE INDEX IX_SHIPMENT_PARTICIPANT_ORGANIZATION_ID ON SHIPMENT_PARTICIPANT (ORGANIZATION_ID);

CREATE UNIQUE INDEX UX_SHIPMENT_PARTICIPANT_LIVE ON SHIPMENT_PARTICIPANT (
    CASE WHEN REVOKED_AT IS NULL THEN SHIPMENT_ID END,
    CASE WHEN REVOKED_AT IS NULL THEN ORGANIZATION_ID END);

CREATE TABLE CUSTODY_EVENT (
    ID                    RAW(16)                        NOT NULL,
    SHIPMENT_ID           RAW(16)                        NOT NULL,
    SEQUENCE_NUMBER       NUMBER(10)                     NOT NULL,
    KIND                  VARCHAR2(24 CHAR)              NOT NULL,
    FROM_ORGANIZATION_ID  RAW(16),
    TO_ORGANIZATION_ID    RAW(16),
    SITE_ID               RAW(16),
    ACTOR_ID              RAW(16)                        NOT NULL,
    OCCURRED_AT           TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    RECORDED_AT           TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    PREVIOUS_HASH         VARCHAR2(64 CHAR)              NOT NULL,
    HASH                  VARCHAR2(64 CHAR)              NOT NULL,
    CREATED_AT            TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_BY            RAW(16)                        NOT NULL,
    UPDATED_AT            TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY            RAW(16),
    CONSTRAINT PK_CUSTODY_EVENT PRIMARY KEY (ID),
    CONSTRAINT FK_CUSTODY_EVENT_SHIPMENT FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENT (ID) ON DELETE CASCADE,
    CONSTRAINT UQ_CUSTODY_EVENT_SEQUENCE UNIQUE (SHIPMENT_ID, SEQUENCE_NUMBER),
    CONSTRAINT CK_CUSTODY_EVENT_KIND CHECK (KIND IN
        ('CREATED', 'DISPATCHED', 'HANDOFF', 'ARRIVED', 'DELIVERED', 'REJECTED', 'CANCELLED',
         'COMPENSATION')),
    CONSTRAINT CK_CUSTODY_EVENT_SEQUENCE CHECK (SEQUENCE_NUMBER > 0),
    CONSTRAINT CK_CUSTODY_EVENT_HASH_BLANK CHECK (TRIM(HASH) IS NOT NULL),
    CONSTRAINT CK_CUSTODY_EVENT_PREVIOUS_BLANK CHECK (TRIM(PREVIOUS_HASH) IS NOT NULL)
);

CREATE INDEX IX_CUSTODY_EVENT_SHIPMENT_ID ON CUSTODY_EVENT (SHIPMENT_ID);

CREATE TABLE HANDOFF_REQUEST (
    ID                    RAW(16)                        NOT NULL,
    SHIPMENT_ID           RAW(16)                        NOT NULL,
    FROM_ORGANIZATION_ID  RAW(16)                        NOT NULL,
    TO_ORGANIZATION_ID    RAW(16)                        NOT NULL,
    CODE_HASH             VARCHAR2(64 CHAR)              NOT NULL,
    STATUS                VARCHAR2(20 CHAR)              NOT NULL,
    EXPIRES_AT            TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    RESOLVED_AT           TIMESTAMP(6) WITH TIME ZONE,
    LOCK_VERSION          NUMBER(10)                     DEFAULT 0 NOT NULL,
    CREATED_AT            TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_BY            RAW(16)                        NOT NULL,
    UPDATED_AT            TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY            RAW(16),
    CONSTRAINT PK_HANDOFF_REQUEST PRIMARY KEY (ID),
    CONSTRAINT FK_HANDOFF_REQUEST_SHIPMENT FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENT (ID) ON DELETE CASCADE,
    CONSTRAINT FK_HANDOFF_REQUEST_FROM_ORGANIZATION FOREIGN KEY (FROM_ORGANIZATION_ID) REFERENCES ORGANIZATION (ID),
    CONSTRAINT FK_HANDOFF_REQUEST_TO_ORGANIZATION FOREIGN KEY (TO_ORGANIZATION_ID) REFERENCES ORGANIZATION (ID),
    CONSTRAINT CK_HANDOFF_REQUEST_STATUS CHECK (STATUS IN
        ('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED')),
    CONSTRAINT CK_HANDOFF_REQUEST_CODE_BLANK CHECK (TRIM(CODE_HASH) IS NOT NULL)
);

CREATE INDEX IX_HANDOFF_REQUEST_SHIPMENT_ID ON HANDOFF_REQUEST (SHIPMENT_ID);

CREATE INDEX IX_HANDOFF_REQUEST_FROM_ORGANIZATION_ID ON HANDOFF_REQUEST (FROM_ORGANIZATION_ID);

CREATE INDEX IX_HANDOFF_REQUEST_TO_ORGANIZATION_ID ON HANDOFF_REQUEST (TO_ORGANIZATION_ID);

CREATE UNIQUE INDEX UX_HANDOFF_REQUEST_PENDING ON HANDOFF_REQUEST (
    CASE WHEN STATUS = 'PENDING' THEN SHIPMENT_ID END);
