CREATE TABLE SENSOR_DEVICE (
    ID                         RAW(16)                        NOT NULL,
    ORGANIZATION_ID            RAW(16)                        NOT NULL,
    SERIAL_NUMBER              VARCHAR2(60 CHAR)              NOT NULL,
    MODEL                      VARCHAR2(80 CHAR)              NOT NULL,
    FIRMWARE                   VARCHAR2(40 CHAR)              NOT NULL,
    STATUS                     VARCHAR2(20 CHAR)              NOT NULL,
    SAMPLING_INTERVAL_SECONDS  NUMBER(6)                      NOT NULL,
    CALIBRATED_AT              TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    DELETED_AT                 TIMESTAMP(6) WITH TIME ZONE,
    CREATED_AT                 TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_BY                 RAW(16)                        NOT NULL,
    UPDATED_AT                 TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY                 RAW(16),
    CONSTRAINT PK_SENSOR_DEVICE PRIMARY KEY (ID),
    CONSTRAINT FK_SENSOR_DEVICE_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID),
    CONSTRAINT CK_SENSOR_DEVICE_STATUS CHECK (STATUS IN ('ACTIVE', 'MAINTENANCE', 'RETIRED')),
    CONSTRAINT CK_SENSOR_DEVICE_SERIAL_BLANK CHECK (TRIM(SERIAL_NUMBER) IS NOT NULL),
    CONSTRAINT CK_SENSOR_DEVICE_MODEL_BLANK CHECK (TRIM(MODEL) IS NOT NULL),
    CONSTRAINT CK_SENSOR_DEVICE_FIRMWARE_BLANK CHECK (TRIM(FIRMWARE) IS NOT NULL),
    CONSTRAINT CK_SENSOR_DEVICE_SAMPLING CHECK (SAMPLING_INTERVAL_SECONDS > 0)
);

CREATE INDEX IX_SENSOR_DEVICE_ORGANIZATION_ID ON SENSOR_DEVICE (ORGANIZATION_ID);

CREATE UNIQUE INDEX UX_SENSOR_DEVICE_SERIAL_LIVE ON SENSOR_DEVICE (
    CASE WHEN DELETED_AT IS NULL THEN ORGANIZATION_ID END,
    CASE WHEN DELETED_AT IS NULL THEN UPPER(SERIAL_NUMBER) END);

CREATE TABLE DEVICE_ASSIGNMENT (
    ID           RAW(16)                        NOT NULL,
    DEVICE_ID    RAW(16)                        NOT NULL,
    SHIPMENT_ID  RAW(16)                        NOT NULL,
    MIN_CELSIUS  NUMBER(5,2)                    NOT NULL,
    MAX_CELSIUS  NUMBER(5,2)                    NOT NULL,
    ATTACHED_AT  TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    DETACHED_AT  TIMESTAMP(6) WITH TIME ZONE,
    CREATED_AT   TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_BY   RAW(16)                        NOT NULL,
    UPDATED_AT   TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY   RAW(16),
    CONSTRAINT PK_DEVICE_ASSIGNMENT PRIMARY KEY (ID),
    CONSTRAINT FK_DEVICE_ASSIGNMENT_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES SENSOR_DEVICE (ID),
    CONSTRAINT CK_DEVICE_ASSIGNMENT_WINDOW CHECK (DETACHED_AT IS NULL OR DETACHED_AT > ATTACHED_AT),
    CONSTRAINT CK_DEVICE_ASSIGNMENT_RANGE CHECK (MIN_CELSIUS < MAX_CELSIUS)
);

CREATE INDEX IX_DEVICE_ASSIGNMENT_DEVICE_ID ON DEVICE_ASSIGNMENT (DEVICE_ID);

CREATE INDEX IX_DEVICE_ASSIGNMENT_SHIPMENT_ID ON DEVICE_ASSIGNMENT (SHIPMENT_ID);

CREATE UNIQUE INDEX UX_DEVICE_ASSIGNMENT_ACTIVE ON DEVICE_ASSIGNMENT (
    CASE WHEN DETACHED_AT IS NULL THEN DEVICE_ID END);

CREATE TABLE READING_BATCH (
    ID               RAW(16)                        NOT NULL,
    ORGANIZATION_ID  RAW(16)                        NOT NULL,
    DEVICE_ID        RAW(16)                        NOT NULL,
    IDEMPOTENCY_KEY  VARCHAR2(80 CHAR)              NOT NULL,
    STATUS           VARCHAR2(20 CHAR)              NOT NULL,
    RECEIVED_COUNT   NUMBER(8)                      NOT NULL,
    ACCEPTED_COUNT   NUMBER(8)                      NOT NULL,
    DISCARDED_COUNT  NUMBER(8)                      NOT NULL,
    RECEIVED_AT      TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_AT       TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_BY       RAW(16)                        NOT NULL,
    UPDATED_AT       TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY       RAW(16),
    CONSTRAINT PK_READING_BATCH PRIMARY KEY (ID),
    CONSTRAINT FK_READING_BATCH_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID),
    CONSTRAINT FK_READING_BATCH_DEVICE FOREIGN KEY (DEVICE_ID) REFERENCES SENSOR_DEVICE (ID),
    CONSTRAINT UQ_READING_BATCH_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT CK_READING_BATCH_STATUS CHECK (STATUS IN ('ACCEPTED', 'PARTIAL', 'REJECTED', 'REPLAYED')),
    CONSTRAINT CK_READING_BATCH_KEY_BLANK CHECK (TRIM(IDEMPOTENCY_KEY) IS NOT NULL),
    CONSTRAINT CK_READING_BATCH_COUNTS CHECK (RECEIVED_COUNT >= 0 AND ACCEPTED_COUNT >= 0
        AND DISCARDED_COUNT >= 0)
);

CREATE INDEX IX_READING_BATCH_ORGANIZATION_ID ON READING_BATCH (ORGANIZATION_ID);

CREATE INDEX IX_READING_BATCH_DEVICE_ID ON READING_BATCH (DEVICE_ID);

CREATE TABLE TEMPERATURE_READING (
    ID               RAW(16)                        NOT NULL,
    ORGANIZATION_ID  RAW(16)                        NOT NULL,
    DEVICE_ID        RAW(16)                        NOT NULL,
    SHIPMENT_ID      RAW(16)                        NOT NULL,
    BATCH_ID         RAW(16)                        NOT NULL,
    CELSIUS          NUMBER(5,2)                    NOT NULL,
    MEASURED_AT      TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_AT       TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_BY       RAW(16)                        NOT NULL,
    UPDATED_AT       TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY       RAW(16),
    CONSTRAINT PK_TEMPERATURE_READING PRIMARY KEY (ID),
    CONSTRAINT CK_TEMPERATURE_READING_CELSIUS CHECK (CELSIUS BETWEEN -100 AND 100)
);

CREATE UNIQUE INDEX UX_TEMPERATURE_READING_SAMPLE
    ON TEMPERATURE_READING (DEVICE_ID, SYS_EXTRACT_UTC(MEASURED_AT));

CREATE INDEX IX_TEMPERATURE_READING_SHIPMENT ON TEMPERATURE_READING (SHIPMENT_ID, MEASURED_AT);

CREATE INDEX IX_TEMPERATURE_READING_BATCH_ID ON TEMPERATURE_READING (BATCH_ID);

CREATE INDEX IX_TEMPERATURE_READING_ORGANIZATION_ID ON TEMPERATURE_READING (ORGANIZATION_ID);

CREATE TABLE EXCURSION (
    ID                    RAW(16)                        NOT NULL,
    ORGANIZATION_ID       RAW(16)                        NOT NULL,
    SHIPMENT_ID           RAW(16)                        NOT NULL,
    KIND                  VARCHAR2(20 CHAR)              NOT NULL,
    STATUS                VARCHAR2(20 CHAR)              NOT NULL,
    OPENED_AT             TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CLOSED_AT             TIMESTAMP(6) WITH TIME ZONE,
    OPENED_BY_READING_ID  RAW(16)                        NOT NULL,
    CLOSED_BY_READING_ID  RAW(16),
    PEAK_CELSIUS          NUMBER(5,2)                    NOT NULL,
    DURATION_MINUTES      NUMBER(8)                      NOT NULL,
    CREATED_AT            TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_BY            RAW(16)                        NOT NULL,
    UPDATED_AT            TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY            RAW(16),
    CONSTRAINT PK_EXCURSION PRIMARY KEY (ID),
    CONSTRAINT FK_EXCURSION_ORGANIZATION FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID),
    CONSTRAINT CK_EXCURSION_KIND CHECK (KIND IN ('ABOVE_MAX', 'BELOW_MIN')),
    CONSTRAINT CK_EXCURSION_STATUS CHECK (STATUS IN ('OPEN', 'CLOSED')),
    CONSTRAINT CK_EXCURSION_WINDOW CHECK (CLOSED_AT IS NULL OR CLOSED_AT >= OPENED_AT),
    CONSTRAINT CK_EXCURSION_DURATION CHECK (DURATION_MINUTES >= 0)
);

CREATE INDEX IX_EXCURSION_ORGANIZATION_ID ON EXCURSION (ORGANIZATION_ID);

CREATE INDEX IX_EXCURSION_SHIPMENT_ID ON EXCURSION (SHIPMENT_ID, OPENED_AT);
