CREATE TABLE CERTIFICATE (
    ID                   RAW(16)                        NOT NULL,
    ORGANIZATION_ID      RAW(16)                        NOT NULL,
    SHIPMENT_ID          RAW(16)                        NOT NULL,
    CERTIFICATE_VERSION  NUMBER(6)                      NOT NULL,
    VERDICT              VARCHAR2(24 CHAR)              NOT NULL,
    COVERAGE_PERCENT     NUMBER(5,2)                    NOT NULL,
    CUMULATIVE_MINUTES   NUMBER(8)                      NOT NULL,
    LONGEST_MINUTES      NUMBER(8)                      NOT NULL,
    THRESHOLD_SNAPSHOT   JSON                           NOT NULL,
    EVALUATED_FROM       TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    EVALUATED_TO         TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    ISSUED_AT            TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CONTENT_HASH         VARCHAR2(64 CHAR)              NOT NULL,
    SUPERSEDED_AT        TIMESTAMP(6) WITH TIME ZONE,
    CREATED_AT           TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_BY           RAW(16)                        NOT NULL,
    UPDATED_AT           TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY           RAW(16),
    CONSTRAINT PK_CERTIFICATE PRIMARY KEY (ID),
    CONSTRAINT FK_CERTIFICATE_ORG FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID),
    CONSTRAINT UQ_CERTIFICATE_VERSION UNIQUE (SHIPMENT_ID, CERTIFICATE_VERSION),
    CONSTRAINT CK_CERTIFICATE_VERDICT CHECK (VERDICT IN
        ('PASS', 'PASS_WITH_DEVIATION', 'FAIL')),
    CONSTRAINT CK_CERTIFICATE_COVERAGE CHECK (COVERAGE_PERCENT BETWEEN 0 AND 100),
    CONSTRAINT CK_CERTIFICATE_MINUTES CHECK (CUMULATIVE_MINUTES >= 0
        AND LONGEST_MINUTES >= 0),
    CONSTRAINT CK_CERTIFICATE_WINDOW CHECK (EVALUATED_TO >= EVALUATED_FROM),
    CONSTRAINT CK_CERTIFICATE_HASH_BLANK CHECK (TRIM(CONTENT_HASH) IS NOT NULL),
    CONSTRAINT CK_CERTIFICATE_NUMBER CHECK (CERTIFICATE_VERSION > 0)
);

CREATE INDEX IX_CERTIFICATE_ORGANIZATION_ID ON CERTIFICATE (ORGANIZATION_ID);

CREATE INDEX IX_CERTIFICATE_SHIPMENT_ID ON CERTIFICATE (SHIPMENT_ID);

CREATE INDEX IX_CERTIFICATE_VERDICT ON CERTIFICATE (VERDICT);

CREATE UNIQUE INDEX UX_CERTIFICATE_CURRENT ON CERTIFICATE (
    CASE WHEN SUPERSEDED_AT IS NULL THEN SHIPMENT_ID END);

CREATE TABLE CERTIFICATE_FINDING (
    ID              RAW(16)                        NOT NULL,
    CERTIFICATE_ID  RAW(16)                        NOT NULL,
    CODE            VARCHAR2(40 CHAR)              NOT NULL,
    SEVERITY        VARCHAR2(16 CHAR)              NOT NULL,
    EXCURSION_ID    RAW(16),
    DETAIL          JSON,
    CREATED_AT      TIMESTAMP(6) WITH TIME ZONE    NOT NULL,
    CREATED_BY      RAW(16)                        NOT NULL,
    UPDATED_AT      TIMESTAMP(6) WITH TIME ZONE,
    UPDATED_BY      RAW(16),
    CONSTRAINT PK_CERTIFICATE_FINDING PRIMARY KEY (ID),
    CONSTRAINT FK_CERTIFICATE_FINDING_CERTIFICATE FOREIGN KEY (CERTIFICATE_ID)
        REFERENCES CERTIFICATE (ID) ON DELETE CASCADE,
    CONSTRAINT CK_CERTIFICATE_FINDING_CODE CHECK (CODE IN
        ('EXCURSION_ABOVE_MAX', 'EXCURSION_BELOW_MIN', 'DATA_GAP', 'CALIBRATION_EXPIRED',
         'MISSING_HANDOFF_ACCEPTANCE', 'NO_DEVICE_ASSIGNED')),
    CONSTRAINT CK_CERTIFICATE_FINDING_SEVERITY CHECK (SEVERITY IN ('INFO', 'WARNING', 'CRITICAL'))
);

CREATE INDEX IX_CERTIFICATE_FINDING_CERTIFICATE_ID ON CERTIFICATE_FINDING (CERTIFICATE_ID);
